### ISSUE TITLE
add downloads badge

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/rhof#24]
```
[![NPM Downloads](https://img.shields.io/npm/dt/@gh-conf/rhof.svg)](https://www.npmjs.com/package/@gh-conf/rhof)
```

add the above code in README.md with other badges

**Comment by riya09** [comment]
I am first-timer and I would like to work on this

**Comment by arshadkazmi42** [comment]
@riya09 Cool. Go ahead. Let me know if you need any help with this.

**Comment by riya09** [comment]
When I try to push my branch I get the following message-

ERROR: Permission to gh-conf/rhof.git denied to riya09.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

Please need some help with this issue.

**Comment by arshadkazmi42** [comment]
You should fork this repo then push the changes to your forked repo.
Then you will get option to create pull request on this. Repo. You can check contribution guide in the repo for step by step instructions
