### ISSUE TITLE
Fix formatter

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/rhof#44]
HOF formatter is not replacing username in the image link

```
<a href="https://github.com/arshadkazmi42"><img src="https://github.com/{username}.png" width="30" /></a>
```

Logic for this formatter is in this function https://github.com/gh-conf/rhof/blob/master/lib/format-hof.js#L10-L17

**Comment by pwnb0y** [comment]
assign to me

**Comment by arshadkazmi42** [comment]
@pwnb0y Assigned

**Comment by pwnb0y** [comment]
Hey, @arshadkazmi42  I want to run it for testing purposes How would I do that?

**Comment by pwnb0y** [comment]
I want to try just 
```<a href="https://github.com/arshadkazmi42"><img src={"https://github.com/${username}.png" width="30"} /></a>```

**Comment by arshadkazmi42** [comment]
@pwnb0y You can use tests to verify your fixes.

To run test you can follow this https://github.com/gh-conf/rhof/blob/master/CONTRIBUTING.md

**Comment by pwnb0y** [comment]
hello @arshadkazmi42 I am not able to run a test with the yarn command many errors will occur.
![Screenshot (165)](https://user-images.githubusercontent.com/96813659/194616025-2f95165e-f8f3-4c8d-a179-940a88777aef.png)

**Comment by arshadkazmi42** [comment]
This is a known issue with the esline config we have for this repositoriy. For some reason it breaks in windows.

I will suggest running test using this command

```
node_modules/mocha/bin/mocha tests
```

This will only run the tests and not the eslint

**Comment by pwnb0y** [comment]
thanks, @arshadkazmi42

**Comment by pwnb0y** [comment]
Hey, @arshadkazmi42  please check is it working or not?
