### ISSUE TITLE
Add badges to readme

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/rhof#49]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/gh-conf/rhof`
3. Go to root directory `cd rhof`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by Pranjalmishra30** [comment]
Hi, could I contribute to this issue?

**Comment by pwnb0y** [comment]
i also want to contribute

**Comment by arshadkazmi42** [comment]
@pwnb0y @Pranjalmishra30 claimed the issue first. So I would like to check with him if he is interested otherwise I can assign to you.

@Pranjalmishra30 would you like to work on this?

**Comment by Pranjalmishra30** [comment]
I will find a different issue to work on as @pwnb0y has already finished it.

**Comment by arshadkazmi42** [comment]
Thank you for confirming @Pranjalmishra30 

@pwnb0y assigned the issue to you

**Comment by pwnb0y** [comment]
ok thanks @arshadkazmi42

**Comment by Ayushbajpai19** [comment]
I would like to contribute to this repo

**Comment by arshadkazmi42** [comment]
@Ayushbajpai19 We do not have any pending issues right now. The current open issues are assigned to @pwnb0y
